# Generated by Django 4.1 on 2022-08-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='info',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
